name: CMake on multiple platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  windows:
    runs-on: ${{ matrix.os }}

    concurrency:
      group: ${{ github.head_ref || github.ref_name }}-${{ github.workflow }}-${{ matrix }}
      cancel-in-progress: true

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        build_type: [Debug, Release]

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: >
        cmake -B build
        -DCMAKE_CXX_COMPILER=cl
        -DCMAKE_C_COMPILER=cl
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -DPREVIEW_TEST=ON
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build build --config ${{ matrix.build_type }}

    - name: Test
      working-directory: build
      run: ctest --build-config ${{ matrix.build_type }}

  ubuntu-gcc:
    runs-on: ${{ matrix.os }}

    concurrency:
      group: ${{ github.head_ref || github.ref_name }}-${{ github.workflow }}-${{ matrix }}
      cancel-in-progress: true

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        build_type: [Debug, Release]
        compiler: [gcc]
        gcc_version: [7, 8, 9, 10, 11]

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      env:
        CC: ${{ matrix.compiler }}-${{ matrix.gcc_version }}
        CXX: ${{ matrix.compiler }}-${{ matrix.gcc_version }}
      run: >
        cmake -B build
        -DCMAKE_CXX_COMPILER=${{ env.CXX }}
        -DCMAKE_C_COMPILER=${{ env.CC }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -DPREVIEW_TEST=ON
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build build --config ${{ matrix.build_type }}

    - name: Test
      working-directory: build
      run: ctest --build-config ${{ matrix.build_type }}
